package slackclient_test

import (
	"context"

	"github.com/golang/mock/gomock"
	"github.com/incident-io/golang-client-mocking/slackclient"
	mock_slackclient "github.com/incident-io/golang-client-mocking/slackclient/mock_slackclient"
	"github.com/slack-go/slack"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("ClientFor", func() {
	var (
		ctx context.Context
		sc  *mock_slackclient.MockSlackClient
	)

	BeforeEach(func() {
		ctx = context.Background()
	})

	// Create a mock and assign it to the sc variable at the start of each test
	slackclient.MockSlackClient(&ctx, &sc, nil)

	Describe("mocking a channel call", func() {
		// Apply an expectation in the BeforeEach, before the test runs
		BeforeEach(func() {
			sc.EXPECT().GetConversationInfoContext(gomock.Any(), "CH123", false).
				Return(&slack.Channel{
					GroupConversation: slack.GroupConversation{
						Name: "my-channel",
						Conversation: slack.Conversation{
							NameNormalized: "my-channel",
							ID:             "CH123",
						},
					},
				}, nil).Times(1)
		})

		Specify("returns a client that responds with the mock", func() {
			client, err := slackclient.ClientFor(ctx, "OR123")
			Expect(err).NotTo(HaveOccurred(), "Slack client should have built with no error")

			channel, err := client.GetConversationInfoContext(ctx, "CH123", false)
			Expect(err).NotTo(HaveOccurred())

			// We'll only receive this if the client generated by ClientFor is the mock we
			// configured with a fake response in our BeforeEach.
			Expect(channel.NameNormalized).To(Equal("my-channel"))
		})
	})
})
